### ISSUE TITLE
Condense PR Reminder panel 

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/ostep-dashboard#105]
Currently, the PR Reminder panel's tags have a dedicated line and use up lots of white space. Tags should be shorted to just the priority type and be on the same line as the description.

**Comment by naiuhz** [comment]
Let's discuss what format to agree on.

**Comment by manekenpix** [comment]
I think the labels need a dedicated line since we're supposed to have enough tags in every PR to fill the full line (as you have in this issue, "type: enhancement", "type: discussion").

**Comment by naiuhz** [comment]
Perhaps either the spacing between the lines could be smaller or the size of the tags can be smaller?

**Comment by manekenpix** [comment]
Yes, let's have a discussion about it.
