### ISSUE TITLE
Filter out OSD600 project

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/ostep-dashboard#108]
[OSD600](https://wiki.cdot.senecacollege.ca/wiki/OSD600) is starting a [new project](https://github.com/Seneca-CDOT/telescope) that will probably have more than 50 students working on it (issues, commits, pull requests). Should we filter that repo out since it's technically not an OSTEP project?

**Comment by poftadeh** [comment]
I suggest importing a whitelist and filtering the GitHub API results using it. The whitelist can be placed in `config-files`.
