### ISSUE TITLE
Improve Media Queries

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/ostep-dashboard#46]
Check for at least these resolutions:

- [ ] 4K - 2560px
- [ ] Laptop Large - 1440px
- [ ] Laptop - 1024px
- [ ] Tablet - 768px
- [ ] Mobile Large - 425px
- [ ] Mobile Medium - 375px
- [ ] Mobile Small - 320px

Breakpoints should be added whenever the layout breaks.

Refer to: https://material.io/design/layout/responsive-layout-grid.html#breakpoints

**Comment by miggs125** [comment]
I'll take this if no one is working on it

**Comment by poftadeh** [comment]
Closed in #60
