### ISSUE TITLE
HTTP error codes are being ignored

### ISSUE THREAD

**Issue by belavina** [Seneca-CDOT/ostep-dashboard#50]
Github container ignores Error Status codes (non 20X), these bypass if (err) {..} statement and result in ambiguous errors.

E.g. it happens when github auth token is invalidated (or rate limit gets maxed out) and 401 gets returned.

**Comment by miggs125** [comment]
[Pull Request](https://github.com/Seneca-CDOT/ostep-dashboard/pull/72#issue-285495444)

**Comment by manekenpix** [comment]
Closed by #72
