### ISSUE TITLE
convert css files to sass and refactor code

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/ostep-dashboard#61]
The style files are, specifically App.css is getting rather large and needs to be refactored and modulated in order to keep the codebase maintainable as the project scales

**Comment by Silvyre** [comment]
Hello,

I am a Seneca student currently taking [Topics in Open Source Development](https://wiki.cdot.senecacollege.ca/wiki/DPS909). I have chatted with my professor (@humphd) about contributing to an OSTEP repository for [Hacktoberfest](https://hacktoberfest.digitalocean.com/), and working on this issue for the OSTEP dashboard seems like a great opportunity to do so.

If possible, may I request permission to work on this issue? I would alternatively be happy to drop by CDOT in person to chat more about how I may help out.

Thank you very much,

Rafi

**Comment by humphd** [comment]
cc @manekenpix and @miggs125, who are both in my open source class, and also work or have worked in this repo as well.  Perhaps one of you can help guide @manekenpix so he can contribute too?

**Comment by poftadeh** [comment]
@Silvyre feel free to take on this issue for Hacktoberfest. @miggs125 started a branch on this work some time ago that you may refer to.

**Comment by Silvyre** [comment]
Thank you very much, everyone! I look forward to working with you!

**Comment by manekenpix** [comment]
@humphd yes, no problem. @Silvyre let us know if there's anything we can help you with.

**Comment by miggs125** [comment]
@Silvyre feel free to take it, I started working on it some time ago on [this](https://github.com/Seneca-CDOT/ostep-dashboard/tree/issues/61-convert-css-to-sass) branch. Some of the content on the branch may be outdated. It's been a while since I worked on it.

**Comment by Silvyre** [comment]
@manekenpix @miggs125 Thank you! I'll certainly be in touch!

**Comment by Silvyre** [comment]
Thanks to the help of @miggs125, I have been able to successfully run the OSTEP Dashboard locally via `npm run-script`[`debug`](https://github.com/Seneca-CDOT/ostep-dashboard/blob/master/Dashboard/package.json#L21).

Within the next three weeks, I plan to apply the knowledge I am gaining from a Udemy course (also recommended by @miggs125) to finish the work started on the [issues/61-convert-css-to-sass](https://github.com/Seneca-CDOT/ostep-dashboard/tree/issues/61-convert-css-to-sass) branch.

**Comment by poftadeh** [comment]
@Silvyre good to hear. I've changed #10 to an open `help wanted` issue as well if you're in need of more contributions toward Hacktoberfest. It's a relatively small starter issue that you or anyone else from @humphd 's class are free to take on if interested.
