### ISSUE TITLE
Auth / Express server & container

### ISSUE THREAD

**Issue by belavina** [Seneca-CDOT/ostep-dashboard#7]
- No auth on CDOT network
- Auth for everything else

**Comment by ctyler** [comment]
In the interim, let's restrict access to the research network only, via a firewall rule.

**Comment by ctyler** [comment]
In case it's not obvious, this is needed so that we don't leak information about commits to private repositories to the public.

**Comment by ctyler** [comment]
Let me be clear: this is a BLOCKER, and the dashboard CANNOT be used until it is fixed.
