### ISSUE TITLE
Infrastructure display: false positives

### ISSUE THREAD

**Issue by ctyler** [Seneca-CDOT/ostep-dashboard#73]
The infra display is showing an "up" status for machines that are down or even non-existant.

**Comment by poftadeh** [comment]
The dashboard runs this command `ssh -o "StrictHostKeyChecking no" -i id_rsa -p 22 arif@ehl.cdot.systems hostname`

which results in this error:
`Load key "id_rsa": invalid format
arif@ehl.cdot.systems: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).`

**Comment by poftadeh** [comment]
Fixed in #78
