### ISSUE TITLE
Close inactive branches

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/ostep-dashboard#77]
We should determine which branches can be closed and close them. For example, the HTTP ignored errors issue has had a PR submitted and merged to master. We should remove this branch.

**Comment by poftadeh** [comment]
Anything that shows up in a `git branch --merged` is probably safe to delete. We should clear all the stray branches since people are developing off their forks now.

**Comment by poftadeh** [comment]
Issue resolved in standards meeting: everyone is encouraged to develop off their forks and create pull requests to the upstream repo.
