### ISSUE TITLE
Pull request reminder endpoint

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/ostep-dashboard#87]
Uses the following structure: 
```
 [
    {
      title: "Add PR reminders",
      author: "Olga",
      date: "2019-01-01",
      project: "ostep-dashboard",
      reviewers: [
            { name: "John", status: "pending" },
            { name: "Jane", status: "approved" },  
            { name: "Joe", status: "requestedChanges" } 
      ],
      priority: "high",
      url: "http://link-to-pr.com",
    },
    // more PRs here
  ] 
```
For `priority`, match regex to the array of labels (e.g. `Priority: Low` or `high priority`). Sort the array of PRs by their priority from highest to lowest. If an issue is missing a priority label, use medium as the default.

**Comment by manekenpix** [comment]
I think we could use RA's avatars here too like in `help-wanted`. Thoughts?

**Comment by poftadeh** [comment]
Sure, that sounds good.
