### ISSUE TITLE
Add pull Request reminder panel

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/ostep-dashboard#92]
Now that the endpoint is complete, we need to create the necessary frontend components to display the data:

- [ ] Create a new panel component with title `Pending Pull Requests`. Follow the structure of other panel components for now. 
- [ ] Show the following info: `issue title` (truncated after a certain length, i.e. `text-overflow: ellipsis`), `number`, `author`, `description`, `date`, `project`, `priority`, `url`, and `reviewers` (can use icons for this last one and `author` to save space). One pull request per line to save space.
- [ ] Make panel responsive.
- [ ] (Optional) Add dummy data to `dummy-data.js` for debug mode.

**Comment by manekenpix** [comment]
I'd like to do this for Hacktoberfest.

**Comment by poftadeh** [comment]
Sure, go for it.
