### ISSUE TITLE
Infrastructure Panel Discrepancies

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/ostep-dashboard#97]
Infrastructure is giving incorrect information on the status of the servers and workstations.

Steps to reproduce the bug:
1. Go to Dashboard
2. Look at the Infrastructure panel
3. Note which servers and workstations are online and offline
4. Attempt to connect to said servers and workstations
5. Report any discrepancies

Current discrepancies:
- aarchie and xerxes are online but reported offline
- narnia is offline but reported online

Expected results:
- aarchie, xerxes and narnia's status need to be correct

Environment:
 - OS: Fedora
 - Browser: Google Chrome

**Comment by manekenpix** [comment]
I think we could include #4 here.
